public class FraudAssessmentDetails{
    public ApplicationDetails applicationDetails;
    public BranchDetails branchDetails;
    public String rafUniqueKey;
    public String bpId;
    public String lastAnalyst;
    public String lastTeamLeader;
    public String lastManager;
    public String lastInvestigatingOfficer;
    public Channel channel;
    public String prevFlowAction;
    public String priority;
    public Documents documents;
    public ApplicationNotes applicationNotes;
    public int stepCounter;
    public boolean isApplicationEscalated;
    public String customerStatus;
    public ReferralOutcome referralOutcome;
    public Metadata @metadata;
}
