public class Item{
    public String itemId;
    public ProdType prodType;
    public ProdName prodName;
    public double offerLimitMin;
    public DeclineReasons declineReasons;
    public String creditStatus;
    public String buttonVisibility;
    public Metadata @metadata;
    public String applicationStatus;
    public String name;
    public String value;
    public String fileName;
    public String documentType;
    public String documentID;
    public String contentURL;
    public String createdDate;
    public String uploadedBy;
    public boolean isBranchUploaded;
    public boolean kycIndicator;
    public String kycVerificationDate;
    public String kycVerifiedBy;
    public String docucmentTypeDescription;
    public NoteInfo noteInfo;
}
