public class PersonalDetails{
    public Title title;
    public String initials;
    public String firstName;
    public String surname;
    public Date dob;
    public Language language;
    public Gender gender;
    public MaritalStatus maritalStatus;
    public IdType idType;
    public String idNumber;
    public String studentInd;
    public String medicalProfQualInd;
    public String cellNumber;
    public String email;
    public String kycStatus;
    public Origin origin;
    public String residentInd;
    public String tempResidentInd;
    public String preferredBranch;
    public Metadata @metadata;
}
