public class Root{
    @JsonProperty("COA_Compliance_PID") 
    public Object cOA_Compliance_PID;
    public String currentTaskId;
    public Object relatedPartyIDNotFound;
    public NotifyCreditOfficerReq notifyCreditOfficerReq;
    public NotifyCreditOfficerRes notifyCreditOfficerRes;
    public boolean isBRCPLimitIncrease;
    public String productName;
    public boolean isCollateralRequired;
    public String mktSegmentResponse;
    public String trackingEvent_assignedDate;
    public ReferralRqRs referralRqRs;
    public CatchmentRoutingDetails catchmentRoutingDetails;
    public String assignedUser;
    public String accountExecEmailAddress;
    public CreditAssessmentDetails creditAssessmentDetails;
    public double totalUnsecuredExposure;
    public String taskAuditOwner;
    public String officerEmailAddress;
    public int taskOwnercounter;
    public SetTrackingEventRq setTrackingEventRq;
    public SetTrackingEventRs setTrackingEventRs;
    public String bpId;
    public String creditOutcomeResponse;
    public String bpGUID;
    public String taskSubject;
    public String originatingProcess_BRCPLimitIncrease;
    public String flowAction;
    public String taskProductName;
    public RelatedPartiesSummary relatedPartiesSummary;
    public Object bureauApiFraudAlert;
    public boolean studentLoanIndicator;
    public Decision decision;
    public int reworkCounter;
    public int retryCount;
    @JsonProperty("COA_Fulfillment_PID") 
    public Object cOA_Fulfillment_PID;
    public Object accountNumber;
    public String processID;
    public String testFlowAction;
    public String originatingCenter;
    public BureauDetail bureauDetail;
    public Object finalTermLoan;
}
