package com.backend.cbz.LoggerMessage;
public class Logger{
    public String initializedLogger;
    public String applicationMode;
    public String logGuid;
    public String bpmFeatureTeam;
    public String serviceType;
    public String callerHostname;
    public String callerAcronym;
    public String upn;
    public String digitalId;
    public String empNo;
    public String consumerBpmApplication;
    public String orchestrationAppName;
    public String callerProcessInstanceId;
    public String location;
    public String message;
    public String endpoint;
    public String bpelName;
    public String payload;
    public String response;
    public HeaderDetailsJSON headerDetailsJSON;
    public String userId;
    public String errorBO;
    public String businessFunction;
    public String startTime;
    public String endTime;
    public Metadata @metadata;
}
